name: Node.js React CI

on:
    pull_request:
        branches: ['main']

jobs:
    build:
        name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x]
                os: ['ubuntu-latest', 'windows-latest']

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: cd frontend
            - run: npm install -g npm@8.3.1
            - run: npm ci
